version: '3.8'

services:
  kyc-service:
    build: .
    container_name: plokymarket-kyc-ai
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - plokymarket-kyc-net

networks:
  plokymarket-kyc-net:
    driver: bridge
